// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvuaweuwotjckowukxlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2dWF3ZXV3b3RqY2tvd3VreGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjk4MjcsImV4cCI6MjA2NTc0NTgyN30.g2wzrxOpVbcmzws_c7OeFXBbWjLV03VYykL9RCf717Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);